use std::path::{Path, PathBuf};

/// Generate the research-pack embedding table from the pack index, so adding
/// a research pack is a data change (one compiled file plus one index line)
/// instead of a Rust edit. `src/elm/discovery/research.rs` includes the
/// generated `EMBEDDED` table; the index itself stays embedded there.
fn emit_research_packs() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let data_dir = manifest
        .join("../../../packages/uds-map/data")
        .canonicalize()
        .unwrap_or_else(|error| {
            panic!("packages/uds-map/data is not reachable from {manifest:?}: {error}")
        });
    let index_path = data_dir.join("research-packs.json");
    println!("cargo:rerun-if-changed={}", index_path.display());

    let raw = std::fs::read_to_string(&index_path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", index_path.display()));
    let index: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|error| panic!("{} is malformed: {error}", index_path.display()));
    assert_eq!(
        index["schema_version"].as_u64(),
        Some(1),
        "unsupported research index schema in {}",
        index_path.display()
    );
    let packs = index["packs"]
        .as_array()
        .unwrap_or_else(|| panic!("{} has no packs array", index_path.display()));

    let mut entries = String::new();
    let mut seen: Vec<&str> = Vec::new();
    for pack in packs {
        let name = pack.as_str().unwrap_or_else(|| {
            panic!(
                "{} lists a non-string pack entry {pack}",
                index_path.display()
            )
        });
        assert!(
            !name.contains("..") && !name.starts_with('/') && !name.contains('\\'),
            "unsafe research pack path in {}: {name}",
            index_path.display()
        );
        assert!(
            !seen.contains(&name),
            "{} lists {name} twice",
            index_path.display()
        );
        seen.push(name);
        let path = data_dir.join(name);
        assert!(
            path.is_file(),
            "research index lists {name}, but {} does not exist -- \
             compile the pack into packages/uds-map/data/research/, or drop \
             the line from packages/uds-map/data/research-packs.json",
            path.display()
        );
        println!("cargo:rerun-if-changed={}", path.display());
        entries.push_str(&format!(
            "    ({}, include_str!({})),\n",
            rust_string(name),
            rust_string(&path.to_string_lossy()),
        ));
    }
    assert!(
        !entries.is_empty(),
        "{} lists no research packs",
        index_path.display()
    );

    let generated = format!(
        "// @generated by build.rs from packages/uds-map/data/research-packs.json.\n\
         const EMBEDDED: &[(&str, &str)] = &[\n{entries}];\n"
    );
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("research_packs.rs");
    write_if_changed(&out, &generated);
}

/// Keep the file's mtime stable when nothing changed, so an unrelated
/// rebuild does not invalidate every downstream unit.
fn write_if_changed(path: &Path, contents: &str) {
    if std::fs::read_to_string(path).is_ok_and(|current| current == contents) {
        return;
    }
    std::fs::write(path, contents)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", path.display()));
}

fn rust_string(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn main() {
    emit_research_packs();
    tauri_build::build()
}
