//! Read-only research candidates used to prioritize discovery.
//!
//! This is intentionally separate from `packs`: an entry here is evidence
//! about where to look, never a trusted module or decode. Callers must supply
//! a matching platform for platform-scoped routes. Candidate DIDs are only
//! suitable for observations/hypotheses.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeSet;
use std::sync::OnceLock;

const INDEX_RAW: &str = include_str!("../../../../../../packages/uds-map/data/research-packs.json");
// The embedding table is generated by `build.rs` from the same index:
// adding a pack is a new file in `packages/uds-map/data/research/` plus a
// line in `research-packs.json`, with no Rust edit. A listed file that
// does not exist fails the build with the path it looked for.
include!(concat!(env!("OUT_DIR"), "/research_packs.rs"));

#[derive(Debug, Deserialize)]
struct ResearchIndex {
    schema_version: u32,
    packs: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct ResearchPack {
    pub schema_version: u32,
    pub pack_id: String,
    pub version: u32,
    pub research_date: String,
    pub mode: String,
    pub policy: ResearchPolicy,
    pub profiles: Vec<CandidateProfile>,
    pub claims: Vec<ResearchClaim>,
}

#[derive(Debug, Deserialize)]
pub struct ResearchPolicy {
    pub read_only: bool,
    pub default_session_only: bool,
    pub max_outstanding_requests: u32,
    pub forbidden_services: Vec<String>,
    pub candidate_decodes_are_hypotheses: bool,
}

#[derive(Debug, Deserialize)]
pub struct CandidateProfile {
    pub brand_id: String,
    pub brand_name: String,
    pub status: String,
    pub wmis: Vec<String>,
    #[serde(default)]
    pub platforms: Vec<CandidatePlatform>,
    pub routes: Vec<CandidateRoute>,
}

#[derive(Debug, Deserialize)]
pub struct CandidatePlatform {
    pub platform_id: String,
    #[serde(default)]
    pub models: Vec<String>,
    #[serde(default)]
    #[allow(dead_code)]
    pub powertrains: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, PartialEq)]
pub struct CandidateRoute {
    pub route_id: String,
    pub platform: String,
    #[serde(default)]
    pub platform_alternatives: Vec<String>,
    #[serde(default)]
    pub exploration_only: bool,
    pub protocol: String,
    pub req: String,
    pub resp: String,
    pub address_extension: Option<String>,
    pub service: String,
    pub session: String,
    pub claim_ids: Vec<String>,
    #[serde(default)]
    pub module_role: Option<String>,
    #[serde(default = "default_true")]
    pub requires_identity: bool,
    #[serde(default)]
    pub candidate_dids: Vec<CandidateDid>,
    #[serde(default)]
    pub knowledge_state: Option<super::state::KnowledgeState>,
    #[serde(default)]
    pub vehicle_fit: Option<super::state::VehicleFit>,
    #[serde(default)]
    pub identity_fit: Option<super::state::IdentityFit>,
    #[serde(default)]
    pub activation: Option<super::state::Activation>,
}

fn default_true() -> bool {
    true
}

/// A research DID may remain a bare identifier, or carry enough hypothesis
/// metadata to tell the verifier what the source claims and how to test it.
/// None of these fields enter the trusted decode path.
#[derive(Clone, Debug, Deserialize, PartialEq)]
#[serde(untagged)]
#[allow(clippy::large_enum_variant)]
pub enum CandidateDid {
    Id(String),
    Detailed(CandidateDidHypothesis),
}

#[derive(Clone, Debug, Deserialize, PartialEq)]
pub struct CandidateDidHypothesis {
    pub did: String,
    #[serde(default)]
    pub semantic: Option<String>,
    #[serde(default)]
    pub decode: Option<Value>,
    /// Only this explicit format marker authorizes evaluation. Unmarked
    /// legacy formulas remain preserved evidence until projected.
    #[serde(default)]
    pub decode_format: Option<String>,
    #[serde(default)]
    pub decoder_variants: Vec<CandidateDecoderVariant>,
    #[serde(default)]
    pub validation: Option<ValidationRecipe>,
    #[serde(default = "default_true")]
    pub automatic_execution_authorized: bool,
    #[serde(default)]
    pub support_status: Option<String>,
    #[serde(default)]
    pub knowledge_state: Option<super::state::KnowledgeState>,
    #[serde(default)]
    pub vehicle_fit: Option<super::state::VehicleFit>,
    #[serde(default)]
    pub identity_fit: Option<super::state::IdentityFit>,
    #[serde(default)]
    pub activation: Option<super::state::Activation>,
    #[serde(default)]
    pub route_status: Option<String>,
    #[serde(default)]
    pub did_status: Option<String>,
    #[serde(default)]
    pub decode_status: Option<String>,
    #[serde(default)]
    pub validation_recipe_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, PartialEq)]
pub struct CandidateDecoderVariant {
    pub variant_id: String,
    #[serde(default)]
    pub signals: Vec<Value>,
    #[serde(default)]
    pub source_refs: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, PartialEq)]
pub struct ValidationRecipe {
    pub kind: String,
    #[serde(default)]
    pub instructions: Vec<String>,
    #[serde(default)]
    pub expected_behavior: Vec<String>,
}

/// A source-proposed decoder that may be evaluated for review but never enters
/// the trusted decode lookup. Claim ids tie every displayed value to evidence.
#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct CandidateDecodeHypothesis {
    pub semantic: Option<String>,
    pub decode: crate::elm::uds_map::Decode,
    pub variant_id: String,
    pub claim_ids: Vec<String>,
    pub source_refs: Vec<String>,
    pub status: &'static str,
}

impl CandidateDid {
    const SUPPORT_STATUSES: [&'static str; 6] = [
        "candidate",
        "source_observed",
        "supported",
        "physically_supported_on_test_vehicle",
        "unsupported",
        "explicitly_unsupported_on_test_vehicle",
    ];

    pub fn did(&self) -> &str {
        match self {
            Self::Id(did) => did,
            Self::Detailed(candidate) => &candidate.did,
        }
    }

    /// Unsupported and explicitly non-executable records remain available as
    /// evidence, but never become vehicle-facing requests.
    pub fn executable(&self) -> bool {
        match self {
            Self::Id(_) => true,
            Self::Detailed(candidate) => {
                candidate.automatic_execution_authorized
                    && matches!(
                        candidate.support_status.as_deref(),
                        None | Some(
                            "candidate"
                                | "source_observed"
                                | "supported"
                                | "physically_supported_on_test_vehicle"
                        )
                    )
            }
        }
    }

    fn support_status_valid(&self) -> bool {
        match self {
            Self::Id(_) => true,
            Self::Detailed(candidate) => candidate
                .support_status
                .as_deref()
                .is_none_or(|status| Self::SUPPORT_STATUSES.contains(&status)),
        }
    }

    pub fn decode_hypotheses(&self, claim_ids: &[String]) -> Vec<CandidateDecodeHypothesis> {
        let Self::Detailed(candidate) = self else {
            return Vec::new();
        };
        if candidate.decode_format.as_deref() != Some("uds_map_v9") {
            return Vec::new();
        }
        let mut hypotheses = Vec::new();
        if let Some(decode) = candidate
            .decode
            .as_ref()
            .and_then(|value| canonical_decode(value).ok())
        {
            hypotheses.push(CandidateDecodeHypothesis {
                semantic: candidate.semantic.clone(),
                decode,
                variant_id: "default".into(),
                claim_ids: claim_ids.to_vec(),
                source_refs: Vec::new(),
                status: "research_hypothesis",
            });
        }
        for variant in &candidate.decoder_variants {
            for signal in &variant.signals {
                if let Ok(decode) = canonical_decode(signal) {
                    hypotheses.push(CandidateDecodeHypothesis {
                        semantic: candidate.semantic.clone(),
                        decode,
                        variant_id: variant.variant_id.clone(),
                        claim_ids: claim_ids.to_vec(),
                        source_refs: variant.source_refs.clone(),
                        status: "research_hypothesis",
                    });
                }
            }
        }
        hypotheses
    }

    pub fn purpose(&self, claim_ids: &[String]) -> String {
        let claims = claim_ids.join(", ");
        match self {
            Self::Id(_) => format!("research candidate only; claims {claims}"),
            Self::Detailed(candidate) => {
                let semantic = candidate.semantic.as_deref().unwrap_or("meaning unknown");
                let validation = candidate
                    .validation
                    .as_ref()
                    .map(|recipe| format!("; validate with {}", recipe.kind))
                    .unwrap_or_default();
                let proposed_decode = candidate
                    .decode
                    .as_ref()
                    .map(|_| "; proposed decode retained as an untrusted hypothesis")
                    .unwrap_or_default();
                format!(
                    "research candidate: {semantic}{proposed_decode}{validation}; claims {claims}"
                )
            }
        }
    }
}

fn canonical_decode(value: &Value) -> Result<crate::elm::uds_map::Decode, String> {
    const KEYS: [&str; 11] = [
        "offset",
        "len",
        "signed",
        "encoding",
        "bit_offset",
        "bit_len",
        "scale",
        "bias",
        "unit",
        "quantity",
        "label",
    ];
    let object = value
        .as_object()
        .ok_or_else(|| "candidate decode must be an object".to_string())?;
    if let Some(key) = object.keys().find(|key| !KEYS.contains(&key.as_str())) {
        return Err(format!("unknown candidate decode field {key}"));
    }
    let decode: crate::elm::uds_map::Decode = serde_json::from_value(value.clone())
        .map_err(|error| format!("invalid candidate decode: {error}"))?;
    if decode.len == 0 || decode.len > 8 || !decode.scale.is_finite() || !decode.bias.is_finite() {
        return Err("candidate decode has invalid length or arithmetic".into());
    }
    Ok(decode)
}

#[derive(Debug, Deserialize)]
pub struct ResearchClaim {
    pub claim_id: String,
    pub exact_claim: String,
    pub knowledge_state: String,
    pub source_fidelity: String,
    pub vehicle_applicability: String,
    pub scope: String,
    #[serde(default)]
    pub action_if_connected: String,
    #[serde(default)]
    pub promotion_test: String,
    pub source: ResearchSource,
}

#[derive(Debug, Deserialize)]
pub struct ResearchSource {
    pub url: String,
    pub revision: String,
    pub retrieved_at: String,
    pub license: String,
}

fn index() -> &'static ResearchIndex {
    static INDEX: OnceLock<ResearchIndex> = OnceLock::new();
    INDEX.get_or_init(|| {
        serde_json::from_str(INDEX_RAW).expect("data/research-packs.json is malformed")
    })
}

pub fn packs() -> &'static [ResearchPack] {
    static PACKS: OnceLock<Vec<ResearchPack>> = OnceLock::new();
    PACKS.get_or_init(|| {
        assert_eq!(
            index().schema_version,
            1,
            "unsupported research index schema"
        );
        index()
            .packs
            .iter()
            .map(|name| {
                let raw = EMBEDDED
                    .iter()
                    .find(|(file, _)| file == name)
                    .map(|(_, raw)| *raw)
                    .unwrap_or_else(|| panic!("research index lists unembedded pack {name}"));
                let pack: ResearchPack = serde_json::from_str(raw)
                    .unwrap_or_else(|e| panic!("research pack {name} is malformed: {e}"));
                assert_eq!(pack.schema_version, 1, "unsupported schema in {name}");
                assert!(!pack.pack_id.is_empty(), "{name} has no pack id");
                assert!(pack.version > 0, "{name} has no version");
                assert!(
                    !pack.research_date.is_empty(),
                    "{name} has no research date"
                );
                assert_eq!(
                    pack.mode, "candidate_discovery_only",
                    "unsafe mode in {name}"
                );
                assert!(pack.policy.read_only, "{name} is not read-only");
                assert!(pack.policy.default_session_only, "{name} changes session");
                assert_eq!(
                    pack.policy.max_outstanding_requests, 1,
                    "{name} request concurrency"
                );
                assert!(pack.policy.candidate_decodes_are_hypotheses);
                assert!(pack.policy.forbidden_services.iter().any(|s| s == "27"));
                let claims: BTreeSet<&str> = pack
                    .claims
                    .iter()
                    .map(|claim| claim.claim_id.as_str())
                    .collect();
                for profile in &pack.profiles {
                    assert!(!profile.brand_id.is_empty());
                    assert!(!profile.brand_name.is_empty());
                    assert!(!profile.status.is_empty());
                    for route in &profile.routes {
                        assert!(
                            matches!(
                                route.protocol.as_str(),
                                "can11_500"
                                    | "can11_250"
                                    | "can29_normal_fixed"
                                    | "can29_target_byte"
                                    | "can29_custom"
                            ),
                            "unsupported protocol {} on {}",
                            route.protocol,
                            route.route_id
                        );
                        assert!(
                            matches!(route.service.as_str(), "21" | "22"),
                            "unsupported read service {} on {}",
                            route.service,
                            route.route_id
                        );
                        assert!(
                            u32::from_str_radix(&route.req, 16).is_ok()
                                && u32::from_str_radix(&route.resp, 16).is_ok(),
                            "non-hex route address on {}: {}/{}",
                            route.route_id,
                            route.req,
                            route.resp
                        );
                        assert!(route
                            .claim_ids
                            .iter()
                            .all(|id| claims.contains(id.as_str())));
                        assert!(route.candidate_dids.iter().all(|did| u16::from_str_radix(
                            did.did(),
                            16
                        )
                        .is_ok()));
                        assert!(
                            route
                                .candidate_dids
                                .iter()
                                .all(CandidateDid::support_status_valid),
                            "unknown candidate support_status on {}",
                            route.route_id
                        );
                        for candidate in &route.candidate_dids {
                            if let CandidateDid::Detailed(candidate) = candidate {
                                if candidate.decode_format.as_deref() == Some("uds_map_v9") {
                                    assert!(
                                        candidate.decode.is_some()
                                            || !candidate.decoder_variants.is_empty(),
                                        "candidate decode format without formula on {} DID {}",
                                        route.route_id,
                                        candidate.did
                                    );
                                    if let Some(decode) = &candidate.decode {
                                        canonical_decode(decode).unwrap_or_else(|error| {
                                            panic!(
                                                "invalid candidate decode on {} DID {}: {}",
                                                route.route_id, candidate.did, error
                                            )
                                        });
                                    }
                                    for variant in &candidate.decoder_variants {
                                        assert!(
                                            !variant.variant_id.is_empty() && !variant.signals.is_empty(),
                                            "empty candidate decoder variant on {} DID {}",
                                            route.route_id,
                                            candidate.did
                                        );
                                        for signal in &variant.signals {
                                            canonical_decode(signal).unwrap_or_else(|error| {
                                                panic!(
                                                    "invalid candidate decoder variant on {} DID {}: {}",
                                                    route.route_id, candidate.did, error
                                                )
                                            });
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                for evidence in &pack.claims {
                    assert!(!evidence.exact_claim.is_empty());
                    assert!(!evidence.knowledge_state.is_empty());
                    assert!(!evidence.source_fidelity.is_empty());
                    assert!(!evidence.vehicle_applicability.is_empty());
                    assert!(!evidence.scope.is_empty());
                    if pack.pack_id == "existing-brand-hypotheses-v3-delta" {
                        assert!(!evidence.action_if_connected.is_empty());
                        assert!(!evidence.promotion_test.is_empty());
                    }
                    assert!(!evidence.source.url.is_empty());
                    assert!(!evidence.source.revision.is_empty());
                    assert!(!evidence.source.retrieved_at.is_empty());
                    assert!(!evidence.source.license.is_empty());
                }
                pack
            })
            .collect()
    })
}

fn wmi(vin: Option<&str>) -> Option<String> {
    vin.filter(|value| value.len() >= 3)
        .map(|value| value[..3].to_ascii_uppercase())
}

/// Candidate profiles selected only by a source-backed WMI.
pub fn profiles_for_vin(vin: Option<&str>) -> Vec<&'static CandidateProfile> {
    let Some(wmi) = wmi(vin) else {
        return Vec::new();
    };
    let mapped_brand = crate::elm::uds_map::brand_for_vin(vin).map(|brand| brand.id.as_str());
    packs()
        .iter()
        .flat_map(|pack| &pack.profiles)
        .filter(|profile| {
            mapped_brand == Some(profile.brand_id.as_str())
                || profile.wmis.iter().any(|known| known == &wmi)
        })
        .collect()
}

fn normalized_vehicle_fact(value: &str) -> String {
    value
        .trim()
        .to_ascii_lowercase()
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character
            } else {
                '_'
            }
        })
        .collect::<String>()
        .split('_')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("_")
}

/// Resolve a research platform from recorded vehicle facts only when the
/// evidence identifies exactly one platform. Ambiguous matches deliberately
/// return `None`, keeping every platform-scoped route inert.
pub fn platform_for_vehicle_facts(vin: Option<&str>, model: Option<&str>) -> Option<String> {
    let model = normalized_vehicle_fact(model?);
    let matches: BTreeSet<&str> = profiles_for_vin(vin)
        .into_iter()
        .flat_map(|profile| &profile.platforms)
        .filter(|platform| {
            platform
                .models
                .iter()
                .any(|known| normalized_vehicle_fact(known) == model)
        })
        .map(|platform| platform.platform_id.as_str())
        .collect();
    (matches.len() == 1).then(|| (*matches.first().unwrap()).to_string())
}

/// Routes safe to prioritize for this exact context.
///
/// Platform-scoped evidence requires an exact platform match. A route whose
/// platform is `unknown` is make-level research and can be returned after a
/// WMI match, but remains a candidate and never enters trusted lookups.
pub fn routes_for_context(vin: Option<&str>, platform: Option<&str>) -> Vec<CandidateRoute> {
    let mut routes: Vec<CandidateRoute> = profiles_for_vin(vin)
        .into_iter()
        .flat_map(|profile| &profile.routes)
        .filter(|route| {
            !route.exploration_only
                && (route.platform == "unknown"
                    || platform.is_some_and(|actual| actual.eq_ignore_ascii_case(&route.platform)))
        })
        .cloned()
        .collect();
    routes.sort_by(|a, b| {
        a.req
            .cmp(&b.req)
            .then(a.resp.cmp(&b.resp))
            .then(a.route_id.cmp(&b.route_id))
    });
    routes.dedup_by(|a, b| a.route_id == b.route_id);
    routes
}

/// Explicit parked exploration includes broad architecture catalogues after
/// brand matching, but keeps them separate from automatic route selection.
pub fn routes_for_exploration(vin: Option<&str>, platform: Option<&str>) -> Vec<CandidateRoute> {
    let mut routes = routes_for_context(vin, platform);
    routes.extend(
        profiles_for_vin(vin)
            .into_iter()
            .flat_map(|profile| &profile.routes)
            .filter(|route| route.exploration_only)
            .cloned(),
    );
    routes.sort_by(|a, b| {
        a.req
            .cmp(&b.req)
            .then(a.resp.cmp(&b.resp))
            .then(a.route_id.cmp(&b.route_id))
    });
    routes.dedup_by(|a, b| a.req == b.req && a.resp == b.resp && a.service == b.service);
    routes
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    fn vin_for_brand(id: &str) -> String {
        let brand = crate::elm::uds_map::map()
            .brands
            .iter()
            .find(|brand| brand.id == id)
            .unwrap();
        format!("{}EXAMPLE00000000", brand.wmi[0])
    }

    #[test]
    fn index_and_embedded_packs_match_and_are_safe() {
        let listed: Vec<&str> = index().packs.iter().map(String::as_str).collect();
        let embedded: Vec<&str> = EMBEDDED.iter().map(|(name, _)| *name).collect();
        assert_eq!(listed, embedded);
        for pack in packs() {
            assert_eq!(pack.schema_version, 1);
            assert_eq!(pack.mode, "candidate_discovery_only");
            assert!(pack.policy.read_only);
            assert!(pack.policy.default_session_only);
            assert!(pack.policy.candidate_decodes_are_hypotheses);
            assert_eq!(pack.policy.max_outstanding_requests, 1);
            assert!(!pack.pack_id.is_empty());
            assert!(pack.version > 0);
            assert!(!pack.research_date.is_empty());
        }
    }

    /// The embedding table is generated from the index by `build.rs`, so
    /// every listed pack must be present, parse, and be distinguishable.
    /// A pack file listed but missing fails the build itself, before this.
    #[test]
    fn generated_embedding_table_loads_every_index_entry_with_a_unique_pack_id() {
        assert_eq!(EMBEDDED.len(), index().packs.len());
        let mut pack_ids = BTreeSet::new();
        for (name, raw) in EMBEDDED {
            assert!(
                index().packs.iter().any(|listed| listed == name),
                "{name} is embedded but not listed in data/research-packs.json"
            );
            let pack: ResearchPack = serde_json::from_str(raw)
                .unwrap_or_else(|error| panic!("{name} does not parse: {error}"));
            assert!(
                pack_ids.insert(pack.pack_id.clone()),
                "duplicate pack_id {} ({name})",
                pack.pack_id
            );
        }
        assert_eq!(pack_ids.len(), packs().len());
    }

    #[test]
    fn every_route_has_claims_and_only_read_services() {
        let claims: BTreeSet<&str> = packs()
            .iter()
            .flat_map(|pack| &pack.claims)
            .map(|claim| claim.claim_id.as_str())
            .collect();
        for profile in packs().iter().flat_map(|pack| &pack.profiles) {
            for route in &profile.routes {
                assert!(
                    matches!(route.service.as_str(), "21" | "22"),
                    "{}",
                    route.route_id
                );
                assert_eq!(route.session, "default_only", "{}", route.route_id);
                assert!(!route.claim_ids.is_empty(), "{}", route.route_id);
                assert!(route
                    .claim_ids
                    .iter()
                    .all(|id| claims.contains(id.as_str())));
            }
        }
    }

    #[test]
    fn sources_are_immutable_and_claim_ids_are_unique() {
        let mut ids = BTreeSet::new();
        for claim in packs().iter().flat_map(|pack| &pack.claims) {
            assert!(ids.insert(&claim.claim_id), "duplicate {}", claim.claim_id);
            assert_eq!(claim.source.revision.len(), 40);
            assert!(claim.source.url.contains(&claim.source.revision));
            assert!(!claim.source.license.is_empty());
            assert!(!claim.source.retrieved_at.is_empty());
            assert!(!claim.exact_claim.is_empty());
            assert!(!claim.scope.is_empty());
            assert!(!claim.knowledge_state.is_empty());
            assert_ne!(
                claim.knowledge_state, "community_verified",
                "research cannot manufacture fleet verification: {}",
                claim.claim_id
            );
            assert!(!claim.source_fidelity.is_empty());
            assert!(matches!(
                claim.vehicle_applicability.as_str(),
                "untested_by_project" | "partially_project_confirmed"
            ));
        }
    }

    #[test]
    fn platform_routes_require_an_exact_platform_match() {
        assert!(routes_for_context(Some("WP0EXAMPLE00000000"), None).is_empty());
        assert!(routes_for_context(Some("WP0EXAMPLE00000000"), Some("911")).is_empty());
        let routes = routes_for_context(Some("WP0EXAMPLE00000000"), Some("Taycan"));
        assert_eq!(routes.len(), 1);
        assert_eq!(routes[0].route_id, "porsche_taycan_710_77a");
    }

    #[test]
    fn candidates_do_not_enter_the_trusted_decode_path() {
        let route = &routes_for_context(Some("WP0EXAMPLE00000000"), Some("Taycan"))[0];
        assert!(route.candidate_dids.iter().any(|did| did.did() == "2A53"));
        let req = u32::from_str_radix(&route.req, 16).unwrap();
        let resp = u32::from_str_radix(&route.resp, 16).unwrap();
        let did = u16::from_str_radix("2A53", 16).unwrap();
        assert!(
            crate::elm::uds_map::known_did(Some("WP0EXAMPLE00000000"), req, resp, did).is_none()
        );
        assert!(
            super::super::packs::overlay_known_did(Some("WP0EXAMPLE00000000"), req, resp, did)
                .is_none()
        );
    }

    #[test]
    fn detailed_candidates_retain_decode_and_validation_without_authorizing_every_read() {
        let candidate: CandidateDid = serde_json::from_value(serde_json::json!({
            "did": "18A0",
            "semantic": "HV battery temperature",
            "decode_format": "uds_map_v9",
            "decode": {"encoding": "be", "len": 2, "scale": 0.1, "unit": "degC"},
            "validation": {
                "kind": "temperature_cross_check",
                "instructions": ["allow the parked vehicle to equilibrate"],
                "expected_behavior": ["changes slowly"]
            },
            "automatic_execution_authorized": false
        }))
        .unwrap();
        assert_eq!(candidate.did(), "18A0");
        assert!(!candidate.executable());
        let purpose = candidate.purpose(&["S07".into()]);
        assert!(purpose.contains("HV battery temperature"));
        assert!(purpose.contains("untrusted hypothesis"));
        assert!(purpose.contains("temperature_cross_check"));
        let hypothesis = candidate.decode_hypotheses(&["S07".into()]).remove(0);
        assert_eq!(hypothesis.status, "research_hypothesis");
        assert_eq!(hypothesis.claim_ids, ["S07"]);
        assert_eq!(hypothesis.decode.len, 2);
        assert_eq!(hypothesis.decode.scale, 0.1);

        let unknown_formula_field: CandidateDid = serde_json::from_value(serde_json::json!({
            "did": "18A3",
            "decode": {"len": 1, "div": 10}
        }))
        .unwrap();
        assert!(unknown_formula_field.decode_hypotheses(&[]).is_empty());

        let unsupported: CandidateDid = serde_json::from_value(serde_json::json!({
            "did": "18A1",
            "support_status": "explicitly_unsupported_on_test_vehicle"
        }))
        .unwrap();
        assert!(!unsupported.executable());

        let misspelled: CandidateDid = serde_json::from_value(serde_json::json!({
            "did": "18A2",
            "support_status": "unsuported"
        }))
        .unwrap();
        assert!(!misspelled.support_status_valid());
        assert!(!misspelled.executable());
    }

    #[test]
    fn plural_decoder_variants_remain_separate_hypotheses() {
        let candidate: CandidateDid = serde_json::from_value(serde_json::json!({
            "did": "9005",
            "semantic": "pack voltage",
            "decode_format": "uds_map_v9",
            "decoder_variants": [
                {
                    "variant_id": "source-a",
                    "signals": [{"offset": 0, "len": 2, "encoding": "be", "scale": 0.1, "unit": "V"}],
                    "source_refs": ["S01"]
                },
                {
                    "variant_id": "source-b",
                    "signals": [{"offset": 1, "len": 2, "encoding": "be", "scale": 0.01, "unit": "V"}],
                    "source_refs": ["S02"]
                }
            ]
        }))
        .unwrap();
        let hypotheses = candidate.decode_hypotheses(&["claim-a".into()]);
        assert_eq!(hypotheses.len(), 2);
        assert_eq!(hypotheses[0].variant_id, "source-a");
        assert_eq!(hypotheses[0].source_refs, ["S01"]);
        assert_eq!(hypotheses[1].variant_id, "source-b");
        assert_eq!(hypotheses[1].decode.scale, 0.01);
    }

    #[test]
    fn renault_vehicle_facts_select_only_unambiguous_platforms() {
        let vin = vin_for_brand("renault");
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("Twizy")),
            Some("renault_twizy".into())
        );
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("Twingo 3")),
            Some("renault_twingo3_ph2".into())
        );
        assert_eq!(platform_for_vehicle_facts(Some(&vin), Some("Zoe")), None);
        assert_eq!(platform_for_vehicle_facts(Some(&vin), None), None);
    }

    #[test]
    fn renault_pack_preserves_safe_routes_and_only_supported_decodes() {
        let vin = vin_for_brand("renault");
        assert!(routes_for_context(Some(&vin), None).is_empty());

        let routes = routes_for_context(Some(&vin), Some("renault_zoe_ph2"));
        let lbc = routes
            .iter()
            .find(|route| route.route_id == "renault_zoe_ph2_lbc_18dadbf1_18daf1db")
            .unwrap();
        let voltage = lbc
            .candidate_dids
            .iter()
            .find(|candidate| candidate.did() == "9005")
            .unwrap();
        let hypotheses = voltage.decode_hypotheses(&lbc.claim_ids);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].variant_id, "S04-a");
        assert_eq!(hypotheses[0].decode.scale, 0.1);
        assert_eq!(hypotheses[0].decode.unit, "V");

        let megane = routes_for_context(Some(&vin), Some("renault_cmf_cd"));
        let did = megane
            .iter()
            .flat_map(|route| &route.candidate_dids)
            .find(|candidate| candidate.did() == "4B00")
            .unwrap();
        assert!(did.decode_hypotheses(&[]).is_empty());
    }

    #[test]
    fn toyota_pack_surfaces_generation_scoped_routes_and_keeps_plain_models_inert() {
        let vin = vin_for_brand("toyota");
        assert_eq!(platform_for_vehicle_facts(Some(&vin), Some("Prius")), None);
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("Prius XW30")),
            Some("toyota_prius_xw30".into())
        );

        let routes = routes_for_context(Some(&vin), Some("toyota_prius_xw30"));
        assert_eq!(routes.len(), 2);
        let abs = routes
            .iter()
            .find(|route| route.route_id == "toyota_prius_xw30_abs_7b0_7b8")
            .unwrap();
        assert_eq!(abs.service, "21");
        let steering = abs
            .candidate_dids
            .iter()
            .find(|candidate| candidate.did() == "47")
            .unwrap()
            .decode_hypotheses(&abs.claim_ids);
        assert_eq!(steering.len(), 1);
        assert_eq!(steering[0].decode.scale, 0.1);
        assert_eq!(steering[0].decode.bias, -3276.8);

        let ths5 = routes_for_context(Some(&vin), Some("toyota_ths5"));
        assert_eq!(ths5.len(), 1);
        assert!(ths5[0]
            .candidate_dids
            .iter()
            .any(|candidate| candidate.did() == "10A6"));
        assert!(ths5
            .iter()
            .all(|route| route.route_id != "lexus_rx_al30_hybrid_7d2_7da"));
    }

    #[test]
    fn hyundai_group_pack_keeps_egmp_models_and_marques_isolated() {
        let vin = vin_for_brand("hyundai_kia");
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("IONIQ 5")),
            Some("hyundai_ioniq5_ne".into())
        );
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("EV6")),
            Some("kia_ev6_cv".into())
        );
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("GV60")),
            Some("genesis_gv60_jw".into())
        );

        let ioniq = routes_for_context(Some(&vin), Some("hyundai_ioniq5_ne"));
        assert_eq!(ioniq.len(), 3);
        assert!(ioniq
            .iter()
            .any(|route| route.route_id == "hyundai_ioniq5_ne_bms_7e4_7ec"));
        assert!(ioniq
            .iter()
            .all(|route| !route.route_id.starts_with("kia_")));

        let ev6 = routes_for_context(Some(&vin), Some("kia_ev6_cv"));
        assert_eq!(ev6.len(), 3);
        assert!(ev6
            .iter()
            .any(|route| route.route_id == "kia_ev6_cv_vcms_744_74c"));
        assert!(ev6
            .iter()
            .all(|route| !route.route_id.starts_with("hyundai_")));

        assert!(routes_for_context(Some(&vin), Some("genesis_gv60_jw")).is_empty());
    }

    #[test]
    fn hyundai_group_popular_models_stay_model_scoped_despite_shared_dids() {
        let vin = vin_for_brand("hyundai_kia");
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("Kona Electric")),
            Some("hyundai_kona_electric_os".into())
        );
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("Kona")),
            Some("hyundai_kona_os".into())
        );
        assert_eq!(
            platform_for_vehicle_facts(Some(&vin), Some("Sportage")),
            Some("kia_sportage_nq5".into())
        );

        let kona_ev = routes_for_context(Some(&vin), Some("hyundai_kona_electric_os"));
        assert_eq!(kona_ev.len(), 2);
        assert!(kona_ev.iter().any(|route| {
            route.route_id == "hyundai_kona_electric_os_bms_7e4_7ec"
                && route
                    .candidate_dids
                    .iter()
                    .any(|candidate| candidate.did() == "0101")
        }));

        let kona = routes_for_context(Some(&vin), Some("hyundai_kona_os"));
        assert_eq!(kona.len(), 1);
        assert!(kona.iter().all(|route| route.route_id.contains("_tpms_")));
        assert!(kona
            .iter()
            .all(|route| !route.route_id.starts_with("hyundai_kona_electric_")));

        let sportage = routes_for_context(Some(&vin), Some("kia_sportage_nq5"));
        assert_eq!(sportage.len(), 1);
        assert!(sportage
            .iter()
            .all(|route| !route.route_id.contains("ioniq")));
        assert!(routes_for_context(Some(&vin), Some("genesis_g80_rg3")).is_empty());
    }

    #[test]
    fn psa_catalogue_is_exploration_only_and_model_branches_stay_isolated() {
        let vin = vin_for_brand("psa");
        let normal = routes_for_context(Some(&vin), Some("psa_c41_project_observed"));
        assert!(normal.iter().all(|route| !route.exploration_only));

        let exploration = routes_for_exploration(Some(&vin), Some("psa_c41_project_observed"));
        assert!(exploration
            .iter()
            .any(|route| route.route_id == "psa_catalog_airbag_744_644"));
        assert!(exploration
            .iter()
            .all(|route| route.route_id != "psa_mmc_ev_bmu_761_762"));

        let c_zero = platform_for_vehicle_facts(Some(&vin), Some("C-Zero"));
        assert_eq!(c_zero.as_deref(), Some("psa_mmc_ev_ion_czero"));
        let routes = routes_for_exploration(Some(&vin), c_zero.as_deref());
        let battery = routes
            .iter()
            .find(|route| route.route_id == "psa_mmc_ev_bmu_761_762")
            .unwrap();
        assert_eq!(battery.service, "21");
        let soc = battery
            .candidate_dids
            .iter()
            .find(|candidate| candidate.did() == "01")
            .unwrap()
            .decode_hypotheses(&battery.claim_ids);
        assert_eq!(soc[0].decode.scale, 0.5);
        assert_eq!(soc[0].decode.bias, -5.0);
    }

    #[test]
    fn candidate_order_is_deterministic() {
        let first = routes_for_context(Some("SAJEXAMPLE00000000"), Some("Jaguar I-PACE"));
        let second = routes_for_context(Some("SAJEXAMPLE00000000"), Some("Jaguar I-PACE"));
        assert_eq!(first, second);
        let keys: BTreeMap<&str, &str> = first
            .iter()
            .map(|route| (route.req.as_str(), route.route_id.as_str()))
            .collect();
        assert_eq!(keys.len(), first.len());
    }

    #[test]
    fn existing_brand_delta_uses_the_main_maps_wmis_without_copying_them() {
        let routes = routes_for_context(Some(&vin_for_brand("subaru")), None);
        let ids: Vec<&str> = routes.iter().map(|route| route.route_id.as_str()).collect();
        assert_eq!(ids, ["subaru_tpms_753_75b", "subaru_engine_7a2_7aa"]);
    }

    #[test]
    fn supporting_psa_research_does_not_change_the_verified_cars_routes() {
        let routes = routes_for_context(Some(&vin_for_brand("psa")), None);
        assert!(routes.is_empty());
        let claim = packs()
            .iter()
            .flat_map(|pack| &pack.claims)
            .find(|claim| claim.claim_id == "psa.route_grammar.supporting")
            .unwrap();
        assert_eq!(claim.vehicle_applicability, "partially_project_confirmed");
        assert!(claim.action_if_connected.contains("never overwrite C4"));
    }

    /// The two brand packages that used to be Python-generated deltas are
    /// specification packs now (`docs/product/research/<brand>-deep-research-v2/`),
    /// compiled by `research:compile`. Their group-wide route catalogues
    /// carry every CAN platform in the pack, so the compiler marks them
    /// `exploration_only`: they stay out of automatic route selection and
    /// reach the planner through `routes_for_exploration`, which is the call
    /// `plan.rs` makes.
    fn compiled_pack(pack_id: &str) -> &'static ResearchPack {
        packs()
            .iter()
            .find(|pack| pack.pack_id == pack_id)
            .unwrap_or_else(|| panic!("{pack_id} is not indexed in data/research-packs.json"))
    }

    #[test]
    fn seat_research_pack_serves_make_wide_candidates_with_dids() {
        let profile = &compiled_pack("seat-deep-research-runtime-v2").profiles[0];
        assert!(
            profile.routes.len() >= 100,
            "the legacy delta served 100 routes; the pack must not lose any, got {}",
            profile.routes.len()
        );

        // No platform match yet: the trusted map carries no SEAT
        // `platforms[]` entry, so nothing platform-scoped can fire and the
        // catalogue is exploration-only.
        let vin = vin_for_brand("seat");
        assert!(routes_for_context(Some(&vin), None).is_empty());
        let routes = routes_for_exploration(Some(&vin), None);
        assert!(!routes.is_empty(), "expected make-wide SEAT candidates");
        assert!(routes.iter().all(|route| route.exploration_only));
        assert!(
            routes.iter().any(|route| !route.candidate_dids.is_empty()),
            "expected at least one candidate route to carry candidate DIDs"
        );
        // The platform-scoped routes require an exact platform match and
        // must not leak in without one.
        assert!(routes
            .iter()
            .all(|route| route.platform != "seat_mii_electric_shared_up"));

        // With an exact platform match the platform-scoped routes become
        // reachable, and their source decoder survives the migration into
        // the canonical scale/bias language.
        let platform_routes = routes_for_context(Some(&vin), Some("seat_mii_electric_shared_up"));
        assert!(!platform_routes.is_empty());
        assert!(platform_routes
            .iter()
            .all(|route| route.platform == "seat_mii_electric_shared_up"));
        let battery = platform_routes
            .iter()
            .find(|route| route.route_id == "seat_mii_hv_battery_management_7e5_7ed")
            .unwrap();
        let voltage = battery
            .candidate_dids
            .iter()
            .find(|candidate| candidate.did() == "1E3B")
            .unwrap()
            .decode_hypotheses(&battery.claim_ids)
            .remove(0);
        assert_eq!(voltage.decode.scale, 0.25);
        assert_eq!(voltage.decode.unit, "V");
        assert_eq!(voltage.variant_id, "S06-a");
        assert_eq!(
            battery.claim_ids,
            [
                "seat-deep-research.source.s06",
                "seat-deep-research.source.s07"
            ]
        );
    }

    #[test]
    fn vag_research_pack_keeps_physically_disproven_dids_out_of_every_plan() {
        let profile = &compiled_pack("vag-deep-research-runtime-v2").profiles[0];
        assert!(
            profile.routes.len() >= 104,
            "the legacy delta served 104 routes; the pack must not lose any, got {}",
            profile.routes.len()
        );

        let vin = vin_for_brand("vag");
        assert!(routes_for_context(Some(&vin), None).is_empty());
        let make_wide = routes_for_exploration(Some(&vin), None);
        assert!(!make_wide.is_empty(), "expected make-wide VAG candidates");
        assert!(make_wide.iter().all(|route| route.exploration_only));
        assert!(make_wide
            .iter()
            .all(|route| route.platform != "audi_j1" && route.platform != "vw_meb_gen1"));

        // The genuinely new thing this package contributes: real negative
        // evidence from a physically tested vehicle. The pack keeps all 22
        // records in `command-support-evidence.json`; the projection carries
        // the 18 that resolve to a route, and none of those identifiers may
        // become a request on the route that refused it.
        const DISPROVEN: [(&str, &str); 18] = [
            ("audi_j1_awd_control_70f_779", "08A7"),
            ("audi_j1_awd_control_70f_779", "0C0A"),
            ("audi_j1_awd_control_70f_779", "2B1B"),
            ("audi_j1_awd_control_70f_779", "2B1C"),
            ("audi_j1_awd_control_70f_779", "2B1D"),
            ("audi_j1_awd_control_70f_779", "2B1E"),
            ("audi_j1_brakes_abs_esc_713_77d", "1800"),
            ("audi_j1_brakes_abs_esc_713_77d", "1801"),
            ("audi_j1_brakes_abs_esc_713_77d", "1802"),
            ("audi_j1_brakes_abs_esc_713_77d", "1803"),
            ("audi_j1_brakes_abs_esc_713_77d", "1816"),
            ("audi_j1_brakes_abs_esc_713_77d", "1821"),
            ("audi_j1_central_electronics_70e_778", "1945"),
            ("audi_j1_instrument_cluster_714_77e", "202F"),
            ("audi_j1_instrument_cluster_714_77e", "2203"),
            ("audi_j1_instrument_cluster_714_77e", "2294"),
            ("audi_j1_instrument_cluster_714_77e", "229A"),
            ("audi_j1_steering_assist_712_77c", "1812"),
        ];
        let platform_routes = routes_for_exploration(Some(&vin), Some("audi_j1"));
        assert!(
            platform_routes
                .iter()
                .any(|route| route.platform == "audi_j1"),
            "expected audi_j1-scoped candidates with an exact platform match"
        );
        for (route_id, did) in DISPROVEN {
            let route = profile
                .routes
                .iter()
                .find(|route| route.route_id == route_id)
                .unwrap_or_else(|| panic!("{route_id} disappeared from the pack"));
            assert!(
                !route
                    .candidate_dids
                    .iter()
                    .any(|candidate| candidate.did() == did && candidate.executable()),
                "{did} was disproven on a real test vehicle and must never be requested on {route_id}"
            );
        }
        // A DID number refused on one module is not refused on another: the
        // evidence is scoped to the route it was observed on.
        let battery = profile
            .routes
            .iter()
            .find(|route| route.route_id == "audi_j1_hv_battery_7e5_7ed")
            .unwrap();
        assert!(battery
            .candidate_dids
            .iter()
            .any(|candidate| candidate.did() == "1801" && candidate.executable()));
    }
}
