// Guided steps (protocol phase 5). The app cannot press the brake or turn
// the wheel, so it runs the loop around the person who can: one
// instruction at a time, a capture of the open hypotheses on the module,
// then a diff against the baseline. Bytes are never interpreted here — a
// DID only earns "changed" when it is stable inside each condition and
// differs between them. Every capture is saved as a verification run.
//
// The steps are generated by the backend (universal discovery protocol
// section 9) as independent triplets `baseline_before_<i>` / `input_<i>` /
// `baseline_after_<i>` on one module and DID set. Captures are keyed by
// step id; an input is diffed against ITS before-baseline and "returned" is
// judged against ITS after-baseline. Reference DIDs a step names on other
// modules are read right before and right after the primary capture.
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronDown, ChevronRight, CircleAlert, RotateCcw, SkipForward } from "lucide-react";
import { Button, ExpanderButton, Kicker, Mono, Note, Pill, Select, Table, Td, Th, Tr } from "@/components/ui";
import { Reveal, Swap } from "@/motion/components";
import { invoke } from "@/lib/tauri";
import { useT } from "@/i18n";
import { useGuidedSteps, type GuidedStep } from "@/views/lab/plan";
import { RunRow, RunSection } from "@/views/lab/RunRow";

type Reading = { did: string; payloads: Array<string | null>; stable: boolean; outcome: { status: string; nrc: number | null } };
type Capture = { run_id: number | null; plan_version: string; route: string; step: string; condition: string; repeats: number; readings: Reading[] };
/** `[before, after]` hex payloads of one reference DID; null = no answer. */
type ReferenceReads = Record<string, Record<string, [string | null, string | null]>>;
type StoredCapture = Capture & { step_id: string; references: ReferenceReads; reference_errors: string[] };
type UdsHit = { did: number; hex: string; ascii: string };

type Verdict = "changed" | "stable" | "noisy" | "missing";

function classify(baseline: Reading | undefined, current: Reading): Verdict {
  if (!baseline || baseline.payloads.every((p) => p == null) || current.payloads.every((p) => p == null)) return "missing";
  const base = baseline.payloads.filter((p): p is string => p != null);
  const now = current.payloads.filter((p): p is string => p != null);
  if (new Set(base).size !== 1) return "noisy";
  if (now.every((p) => p !== base[0])) return "changed";
  return now.every((p) => p === base[0]) ? "stable" : "noisy";
}

const verdictPill: Record<Verdict, "ok" | "warn" | "info" | "stop"> = { changed: "ok", stable: "info", noisy: "warn", missing: "stop" };

const hex4 = (n: number) => n.toString(16).toUpperCase().padStart(4, "0");
const moduleKey = (address: string) => address.replace("/", "_").toLowerCase();

function tripletOf(script: GuidedStep[], index: number): { before: GuidedStep | null; after: GuidedStep | null } {
  const step = script[index];
  if (!step || step.kind !== "input") return { before: null, after: null };
  const before = script[index - 1]?.kind === "baseline" ? script[index - 1] : null;
  const after = script[index + 1]?.kind === "baseline" ? script[index + 1] : null;
  return { before, after };
}

export function GuidedCorrelation({ connected, vehicleId }: { connected: boolean; vehicleId: number | null }) {
  const t = useT();
  const g = t.lab.guidedCorrelation;
  const tree = useGuidedSteps(vehicleId);
  const [started, setStarted] = useState(false);
  const [moduleAddress, setModuleAddress] = useState<string | null>(null);
  const [stepIndex, setStepIndex] = useState(0);
  // The capture that just landed and is waiting for "Next step".
  const [pendingNext, setPendingNext] = useState(false);
  const [captures, setCaptures] = useState<StoredCapture[]>([]);
  const [confirmed, setConfirmed] = useState<Set<string>>(new Set());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [bytesOpen, setBytesOpen] = useState(false);

  const allSteps = useMemo(() => tree.data?.steps ?? [], [tree.data]);
  const modules = useMemo(() => {
    const seen: string[] = [];
    for (const s of allSteps) if (s.module && !seen.includes(s.module)) seen.push(s.module);
    return seen;
  }, [allSteps]);

  useEffect(() => {
    setModuleAddress((current) => {
      if (current && modules.includes(current)) return current;
      const counts = modules.map((m) => [m, allSteps.filter((s) => s.kind === "input" && s.module === m).length] as const);
      return counts.sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;
    });
  }, [modules, allSteps]);

  const script: GuidedStep[] = useMemo(() => allSteps.filter((s) => s.module === moduleAddress), [allSteps, moduleAddress]);
  const [req, resp] = moduleAddress?.split("/") ?? [null, null];
  const repeats = tree.data?.repeats ?? 3;
  const planVersion = tree.data?.plan_version ?? "";
  const step = script[stepIndex];
  const finished = script.length > 0 && stepIndex >= script.length;
  const latest = captures[captures.length - 1] ?? null;
  const byStep = useMemo(() => new Map(captures.map((c) => [c.step_id, c])), [captures]);
  const targetDids = useMemo(() => (step?.capture.dids ?? []).map((d) => parseInt(d, 16)).filter((n) => Number.isFinite(n)), [step]);
  const needsConfirmation = step?.operator_confirmation != null && !confirmed.has(step.id);

  const readReferences = async (s: GuidedStep) => {
    const reads: Record<string, Record<string, string | null>> = {};
    const errors: string[] = [];
    for (const [address, dids] of Object.entries(s.capture.reference_dids)) {
      const wanted = dids.map((d) => parseInt(d, 16)).filter((n) => Number.isFinite(n));
      if (wanted.length === 0) continue;
      try {
        const hits = await invoke<UdsHit[]>("uds_read_many", { module: moduleKey(address), dids: wanted });
        reads[address] = Object.fromEntries(wanted.map((d) => [hex4(d), hits.find((h) => h.did === d)?.hex ?? null]));
      } catch (cause) {
        errors.push(`${address}: ${String(cause instanceof Error ? cause.message : cause)}`);
      }
    }
    return { reads, errors };
  };

  const capture = async () => {
    if (!req || !resp || !step) return;
    setBusy(true);
    setError(null);
    try {
      const before = await readReferences(step);
      const result = await invoke<Capture>("correlation_capture", {
        req, resp, dids: targetDids, step: step.id, condition: step.condition_label, planVersion, repeats,
      });
      const after = await readReferences(step);
      const references: ReferenceReads = {};
      for (const address of new Set([...Object.keys(before.reads), ...Object.keys(after.reads)])) {
        references[address] = {};
        for (const did of new Set([...Object.keys(before.reads[address] ?? {}), ...Object.keys(after.reads[address] ?? {})])) {
          references[address][did] = [before.reads[address]?.[did] ?? null, after.reads[address]?.[did] ?? null];
        }
      }
      setCaptures((all) => [...all, { ...result, step_id: step.id, references, reference_errors: [...before.errors, ...after.errors] }]);
      setPendingNext(true);
      setBytesOpen(false);
    } catch (cause) {
      setError(String(cause instanceof Error ? cause.message : cause));
    } finally {
      setBusy(false);
    }
  };

  const next = () => {
    setPendingNext(false);
    setStepIndex((i) => i + 1);
  };
  const skip = () =>
    setStepIndex((i) => {
      const n = i + 1;
      return script[n]?.kind === "baseline" && script[i]?.kind === "input" ? n + 1 : n;
    });
  const restart = () => {
    setCaptures([]);
    setStepIndex(0);
    setPendingNext(false);
    setError(null);
  };

  const candidates = useMemo(() => {
    const out: Array<{ condition: string; did: string; before: string; during: string; returned: boolean }> = [];
    script.forEach((s, i) => {
      if (s.kind !== "input") return;
      const c = byStep.get(s.id);
      const { before: beforeStep, after: afterStep } = tripletOf(script, i);
      const before = beforeStep ? byStep.get(beforeStep.id) : undefined;
      const after = afterStep ? byStep.get(afterStep.id) : undefined;
      if (!c || !before) return;
      for (const reading of c.readings) {
        const base = before.readings.find((r) => r.did === reading.did);
        if (classify(base, reading) !== "changed") continue;
        const afterReading = after?.readings.find((r) => r.did === reading.did);
        out.push({
          condition: c.condition,
          did: reading.did,
          before: base?.payloads[0] ?? "",
          during: Array.from(new Set(reading.payloads.filter((p): p is string => p != null))).join(" / "),
          returned: afterReading != null && afterReading.stable && afterReading.payloads[0] === base?.payloads[0],
        });
      }
    });
    return out;
  }, [script, byStep]);

  const latestDiff = useMemo(() => {
    const idx = script.findIndex((s) => s.id === latest?.step_id);
    if (!latest || idx < 0 || script[idx].kind !== "input") return null;
    const beforeStep = tripletOf(script, idx).before;
    const before = beforeStep ? byStep.get(beforeStep.id) : undefined;
    if (!before) return null;
    const rows = latest.readings
      .map((r) => ({ reading: r, base: before.readings.find((b) => b.did === r.did), verdict: classify(before.readings.find((b) => b.did === r.did), r) }))
      .sort((a, b) => Number(b.verdict === "changed") - Number(a.verdict === "changed"));
    return { capture: latest, rows };
  }, [latest, script, byStep]);

  const preconditionText = (s: GuidedStep) => {
    const parts: string[] = [];
    if (s.optional) parts.push(g.preconditionMoves);
    else if (s.kind === "input") parts.push(g.preconditionStationary);
    if (typeof s.precondition.engine === "string") parts.push(g.preconditionEngine(s.precondition.engine));
    return parts.join(" ");
  };
  const referenceRows = (c: StoredCapture) =>
    Object.entries(c.references).flatMap(([address, dids]) => Object.entries(dids).map(([did, [b, a]]) => ({ address, did, before: b, after: a })));

  const canStart = connected && vehicleId != null && allSteps.length > 0;
  const state = !started ? "idle" : finished ? "done" : "steps";
  const changedCount = latestDiff?.rows.filter((r) => r.verdict === "changed").length ?? 0;

  return (
    <>
      <RunSection>
        <RunRow
          label={started ? (finished ? t.lab.run.runAgain : t.lab.run.running) : t.lab.run.startSteps}
          onRun={() => {
            restart();
            setStarted(true);
          }}
          busy={false}
          disabled={!canStart || (started && !finished)}
          note={!connected ? t.lab.run.needsCable : vehicleId == null ? g.nameFirst : t.lab.run.noteGuided}
        >
          {!started && modules.length > 1 && (
            <label className="flex items-center gap-1.5 text-[12px] text-neutral-500">
              {t.lab.run.module}
              <Select
                className="num w-auto min-h-7 py-0.5 text-[12px]"
                value={moduleAddress ?? ""}
                onChange={(e) => {
                  setModuleAddress(e.target.value);
                  setStepIndex(0);
                }}
              >
                {modules.map((m) => (
                  <option key={m} value={m}>
                    {m} · {allSteps.filter((s) => s.kind === "input" && s.module === m).length}
                  </option>
                ))}
              </Select>
            </label>
          )}
        </RunRow>
      </RunSection>

      <Swap k={state} className="flex flex-col gap-3.5 px-[26px] py-6">
        {state === "idle" && (
          <>
            <Note>{g.explainer(repeats)}</Note>
            {connected && vehicleId != null && tree.isSuccess && allSteps.length === 0 && <Note>{g.noSteps}</Note>}
            {step && <Note className="num text-[11.5px]">{t.lab.run.identifiers(targetDids.length)}</Note>}
          </>
        )}

        {state === "steps" && step && (
          <>
            <div className="flex items-center gap-2">
              <Kicker>{g.stepOf(stepIndex + 1, script.length)}</Kicker>
              {step.optional && <Pill variant="info">{g.optional}</Pill>}
              <Pill variant={step.kind === "baseline" ? "info" : "accent"}>{step.kind === "baseline" ? g.baselineTitle : step.id}</Pill>
            </div>
            <div className="max-w-[36ch] font-heading text-[19px] font-medium leading-[1.35]">
              {step.kind === "baseline" ? g.baselineInstruction : step.instruction}
            </div>
            {preconditionText(step) && (
              <Note className="flex items-start gap-1.5">
                <CircleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0 text-warn" aria-hidden="true" />
                {preconditionText(step)}
              </Note>
            )}
            {Object.keys(step.capture.reference_dids).length > 0 && (
              <Note className="num text-[11.5px]">
                {g.references}: {Object.entries(step.capture.reference_dids).map(([m, d]) => `${m} ${d.join(", ")}`).join(" · ")}
              </Note>
            )}

            <Swap k={pendingNext ? "result" : needsConfirmation ? "confirm" : busy ? "counting" : "ready"} className="flex flex-col gap-3.5">
              {!pendingNext && needsConfirmation && (
                <div className="flex flex-col gap-2">
                  <Note>{g.confirmPrompt}</Note>
                  <p className="text-[13.5px]">{step.operator_confirmation}</p>
                  <div className="flex gap-2">
                    <Button onClick={() => setConfirmed((s) => new Set(s).add(step.id))}>{g.confirmYes}</Button>
                    <Button variant="ghost" icon={SkipForward} onClick={skip}>
                      {step.optional ? g.skipOptional : g.skip}
                    </Button>
                  </div>
                </div>
              )}
              {!pendingNext && !needsConfirmation && !busy && (
                <div className="flex flex-wrap items-center gap-2">
                  <Button variant="primary" size="lg" onClick={capture} disabled={!connected || !req || targetDids.length === 0}>
                    {g.capture(step.condition_label)}
                  </Button>
                  {step.kind !== "baseline" && (
                    <Button variant="ghost" icon={SkipForward} onClick={skip}>
                      {step.optional ? g.skipOptional : g.skip}
                    </Button>
                  )}
                  {captures.length > 0 && (
                    <Button variant="ghost" icon={RotateCcw} onClick={restart}>
                      {g.restart}
                    </Button>
                  )}
                </div>
              )}
              {!pendingNext && !needsConfirmation && busy && (
                <div className="flex items-center gap-3.5">
                  <Mono className="text-[40px] leading-none text-accent-300">{repeats}×</Mono>
                  <Note>{g.reading(targetDids.length, repeats)}</Note>
                </div>
              )}
              {pendingNext && latest && (
                <>
                  <div className="flex flex-col gap-2 border-l-2 border-accent-600 pl-[13px]">
                    <Kicker>{t.lab.run.whatChanged}</Kicker>
                    <p className="max-w-[58ch] text-[13.5px] leading-[1.6] text-neutral-200">
                      {latestDiff == null
                        ? g.lastCapture(latest.step_id, String(latest.run_id ?? "—"), latest.readings.filter((r) => r.stable).length, latest.readings.length, latest.repeats)
                        : changedCount > 0
                          ? t.lab.run.changedLine(changedCount, latestDiff.rows.length)
                          : t.lab.run.nothingMoved}
                    </p>
                    {latestDiff && changedCount > 0 && (
                      <Mono className="text-[12px] text-neutral-500">
                        {latestDiff.rows
                          .filter((r) => r.verdict === "changed")
                          .slice(0, 3)
                          .map((r) => `${r.reading.did} · ${r.base?.payloads[0] ?? "—"} → ${r.reading.payloads.map((p) => p ?? "—").join(" / ")}`)
                          .join(" · ")}
                      </Mono>
                    )}
                    {latest.reference_errors.length > 0 && (
                      <p role="alert" className="text-[11.5px] text-warn">
                        {g.referenceUnreachable}: {latest.reference_errors.join(" · ")}
                      </p>
                    )}
                  </div>
                  {latestDiff && latestDiff.rows.length > 0 && (
                    <div className="flex flex-col gap-2">
                      <ExpanderButton open={bytesOpen} onClick={() => setBytesOpen((o) => !o)}>
                        {bytesOpen ? <ChevronDown className="h-3.5 w-3.5" aria-hidden="true" /> : <ChevronRight className="h-3.5 w-3.5" aria-hidden="true" />}
                        {bytesOpen ? t.lab.run.hideBytes : t.lab.run.showBytes}
                      </ExpanderButton>
                      <Reveal when={bytesOpen}>
                        <DiffTable rows={latestDiff.rows} refs={referenceRows(latestDiff.capture)} />
                      </Reveal>
                    </div>
                  )}
                  <div>
                    <Button variant="primary" onClick={next}>
                      {t.lab.run.nextStep}
                    </Button>
                  </div>
                </>
              )}
            </Swap>
          </>
        )}

        {state === "done" && (
          <>
            <div className="flex items-center gap-[9px] text-[13.5px]">
              <CheckCircle2 className="h-[17px] w-[17px] text-ok" aria-hidden="true" />
              <span>{t.lab.run.doneGuided(candidates.length)}</span>
            </div>
            <Note className="text-[11.5px]">{g.complete(captures.length, planVersion)}</Note>
            {candidates.length > 0 && (
              <Table className="text-[12px]">
                <thead>
                  <tr>
                    <Th className="px-2">{g.thCondition}</Th>
                    <Th className="px-2">{g.thDid}</Th>
                    <Th className="px-2">{g.thBaseline}</Th>
                    <Th className="px-2">{g.thDuring}</Th>
                    <Th className="px-2">{g.thReturned}</Th>
                  </tr>
                </thead>
                <tbody>
                  {candidates.map((c) => (
                    <Tr key={`${c.condition}-${c.did}`} className="num">
                      <Td className="px-2 py-1.5">{c.condition}</Td>
                      <Td className="px-2 py-1.5">{c.did}</Td>
                      <Td className="px-2 py-1.5">{c.before}</Td>
                      <Td className="px-2 py-1.5">{c.during}</Td>
                      <Td className="px-2 py-1.5">{c.returned ? <Pill variant="ok">{g.yes}</Pill> : <Pill variant="info">{g.notYet}</Pill>}</Td>
                    </Tr>
                  ))}
                </tbody>
              </Table>
            )}
            <Note className="text-[11.5px]">{g.candidateNote}</Note>
            <div>
              <Button icon={RotateCcw} onClick={restart}>
                {g.newSession}
              </Button>
            </div>
          </>
        )}

        {error && (
          <p role="alert" className="text-[12.5px] text-stop">
            {error}
          </p>
        )}
      </Swap>
    </>
  );
}

function DiffTable({
  rows,
  refs,
}: {
  rows: Array<{ reading: Reading; base: Reading | undefined; verdict: Verdict }>;
  refs: Array<{ address: string; did: string; before: string | null; after: string | null }>;
}) {
  const g = useT().lab.guidedCorrelation;
  return (
    <Table className="text-[12px]">
      <thead>
        <tr>
          <Th className="px-2">{g.thDid}</Th>
          <Th className="px-2">{g.thBaseline}</Th>
          <Th className="px-2">{g.thThisStep}</Th>
          <Th className="px-2">{g.thVerdict}</Th>
        </tr>
      </thead>
      <tbody>
        {rows.map(({ reading, base, verdict }) => (
          <Tr key={reading.did} className="num">
            <Td className="px-2 py-1">{reading.did}</Td>
            <Td className="px-2 py-1">{base?.payloads.join(" · ") ?? "—"}</Td>
            <Td className="px-2 py-1">{reading.payloads.map((p) => p ?? "—").join(" · ")}</Td>
            <Td className="px-2 py-1"><Pill variant={verdictPill[verdict]}>{g.verdict[verdict]}</Pill></Td>
          </Tr>
        ))}
        {refs.map((r) => (
          <Tr key={`${r.address}-${r.did}`} className="num text-neutral-500">
            <Td className="px-2 py-1">{r.address} {r.did}</Td>
            <Td className="px-2 py-1">{r.before ?? "—"}</Td>
            <Td className="px-2 py-1">{r.after ?? "—"}</Td>
            <Td className="px-2 py-1"><Pill variant="info">{g.reference}</Pill></Td>
          </Tr>
        ))}
      </tbody>
    </Table>
  );
}
