import { Zap } from "lucide-react";
import { detectVoltageCluster } from "@/lib/dtc-grouping";
import { useT } from "@/i18n";

// The one clustering hint this app makes: an honest, inspectable note, not a
// hidden reclassification. Renders nothing when nothing qualifies — see
// docs/workflows/diagnose-ux/plan.md for the exact trigger rule and why it's
// deliberately narrow (only codes with a real, direct voltage mechanism).
export function VoltageClusterNote({
  scan,
}: {
  scan: { stored: string[]; pending: string[]; permanent: string[]; voltage?: number | null };
}) {
  const t = useT();
  const cluster = detectVoltageCluster(scan);
  if (!cluster) return null;

  return (
    <div className="flex items-start gap-1.5 rounded-md border border-border bg-muted/50 px-3 py-2 text-xs text-muted-foreground">
      <Zap className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden="true" />
      {/* cluster.note stays English in Phase 1 — generated by
          detectVoltageCluster() in lib/dtc-grouping.ts, same Phase 3
          content boundary (its exact English text is also asserted by
          dtc-grouping.test.ts, so it's not a drive-by string to swap). */}
      <span>
        {cluster.note} {t.diagnose.voltageClusterSuffix}
      </span>
    </div>
  );
}
